# Colores
COLOR_BLANCO = (255, 255, 255)
COLOR_NEGRO = (0, 0, 0)
COLOR_GRIS = (206, 206, 206)
COLOR_AZUL = (30, 136, 229)
COLOR_ROJO = (255,0,0)
COLOR_VERDE = (0,255,0)

#Seteos Juego
ANCHO_PANTALLA = 640
ALTO_PANTALLA = 480
ALTO_TEXTO = 50
TAMAÑO_TEXTO = 20
CANTIDAD_TARJETAS_H = 3
CANTIDAD_TARJETAS_V = 4
CANTIDAD_TARJETAS = int((CANTIDAD_TARJETAS_H*CANTIDAD_TARJETAS_V))
CANTIDAD_TARJETAS_UNICAS = int((CANTIDAD_TARJETAS_H*CANTIDAD_TARJETAS_V)/2)
ANCHO_TARJETA = int(ANCHO_PANTALLA / CANTIDAD_TARJETAS_H)
ALTO_TARJETA =int((ALTO_PANTALLA - ALTO_TEXTO)/ CANTIDAD_TARJETAS_V)
TIEMPO_MOVIMIENTO = 3000
FPS = 60
SEGUNDOS = 30
CANTIDAD_MOVIMIENTOS = 15
CARPETA_RECURSOS = "recursos/"
